---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
  fixme:
    enabled: true
ratings:
  paths:
    - "**.py"
exclude_paths:
  - "/tests"
